### ISSUE TITLE
New LCM download issue, GitHub hosts firmware at /v0.0.1/ but OTA manager looks for /0.0.1/ instead

### ISSUE THREAD

**Issue by LDenissen** [AchimPieters/ESP8266-HomeKit-LED-Strip#3]
AchimPieters/ESP8266-HomeKit-NeoPixel-Light-Strip@version:"0.0.1"
--- ota_compare 
0-0,0.1-0.0
0-0,1-0
1-0
0.0.1 with 0.0.0=1
user_repo='AchimPieters/ESP8266-HomeKit-NeoPixel-Light-Strip' new_version='0.0.1' user_file='main60.bin'
--- ota_get_hash
--- ota_get_file_ex
GET /AchimPieters/ESP8266-HomeKit-NeoPixel-Light-Strip/releases/download/0.0.1/main60.bin.sig HTTP/1.1
Host: github.com

--- ota_connect LocalPort=ebb5 DNS IP:13.250.177.223 local..OK remote..OK SSL..OK set_fd to github.com port 443..OK
sent OK
HTTP/1.1 404 Not Found
date: Fri, 10 Apr 2020 07:46:51 GMT

**Comment by AchimPieters** [comment]
yes: read [this](https://www.studiopieters.nl/esp8266-life-cycle-manager-trouble/) and [this](https://www.studiopieters.nl/esp8266-life-cycle-manager-trouble-update/) you can download this latest version [here](https://github.com/HomeACcessoryKid/life-cycle-manager/blob/master/versions1/1.9.12v/otaboot.bin)
